---
- name: Folder/File/Symlik Creation
  ansible.builtin.file:
     src: "{{ item.src | default(omit) }}"
     dest: "{{ item.dest | default(omit) }}"
     path: "{{ item.path | default(omit) }}"
     owner: "{{ item.owner | default('root') }}"
     group: "{{ item.group | default('root') }}"
     state: "{{ item.type | default('file') }}"
     mode: "{{ item.perm | default(omit) }}"
  loop: "{{ folder_config }}"
